### ISSUE TITLE
tests failing on windows

### ISSUE THREAD

**Issue by HansHammel** [maildev/maildev#151]
```bash

> maildev@0.14.0 test C:\f\MailDev
> istanbul cover node_modules/mocha/bin/_mocha -- -R spec



  API
    Constructor
      √ should accept arguments
      √ should return mailserver object
    listen/end
      √ should start the mailserver
      √ should stop the mailserver
    Email
      √ should receive emails (358ms)
      √ should emit events when receiving emails (116ms)

  email
    √ should handle embedded images with cid (192ms)

  mailserver
    smtp authentication
      1) should require authentication
      2) should authenticate

  middleware
    3) "before all" hook

  7 passing (720ms)
  3 failing

  1) mailserver smtp authentication should require authentication:
     Uncaught Error: connect EADDRNOTAVAIL 0.0.0.0:1025
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)

  2) mailserver smtp authentication should authenticate:
     Uncaught Error: listen EADDRINUSE 0.0.0.0:1025
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at Server._listen2 (net.js:1257:14)
      at listen (net.js:1293:10)
      at net.js:1403:9
      at _combinedTickCallback (internal/process/next_tick.js:77:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  3) middleware "before all" hook:
     Uncaught Error: listen EADDRINUSE 0.0.0.0:1025
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at Server._listen2 (net.js:1257:14)
      at listen (net.js:1293:10)
      at net.js:1403:9
      at _combinedTickCallback (internal/process/next_tick.js:77:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)



=============================================================================
Writing coverage object [C:\f\MailDev\coverage\coverage.json]
Writing coverage reports at [C:\f\MailDev\coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 51.31% ( 254/495 )
Branches     : 30.4% ( 69/227 )
Functions    : 38.74% ( 43/111 )
Lines        : 53.38% ( 253/474 )
================================================================================
npm ERR! Test failed.  See above for more details.
```

EADDRNOTAVAIL - seems to be an error in not shutting down server instances between tests!?

**Comment by soulteary** [comment]
Thank you for your feedback, the current software version has a relatively large update, looking forward to your new feedback. @HansHammel
