### ISSUE TITLE
Maildev crash

### ISSUE THREAD

**Issue by kossa** [maildev/maildev#413]
Hello,

I'm using the latest version of maildev, when I start server it starts, but when I send email through Laravel9/PHP8 the server crash

```
MailDev using directory /var/folders/f8/xnd5vhr93p5dbhys9ng1795h0000gn/T/maildev-7540
MailDev webapp running at http://0.0.0.0:1080
MailDev SMTP Server running at 0.0.0.0:1025
/opt/homebrew/lib/node_modules/maildev/node_modules/smtp-server/lib/smtp-stream.js:34
        this.closed = false;
                    ^

TypeError: Cannot set property closed of #<Writable> which has only a getter
    at new SMTPStream (/opt/homebrew/lib/node_modules/maildev/node_modules/smtp-server/lib/smtp-stream.js:34:21)
    at new SMTPConnection (/opt/homebrew/lib/node_modules/maildev/node_modules/smtp-server/lib/smtp-connection.js:55:24)
    at SMTPServer.connect (/opt/homebrew/lib/node_modules/maildev/node_modules/smtp-server/lib/smtp-server.js:93:26)
    at /opt/homebrew/lib/node_modules/maildev/node_modules/smtp-server/lib/smtp-server.js:84:26
    at Immediate.<anonymous> (/opt/homebrew/lib/node_modules/maildev/node_modules/smtp-server/lib/smtp-server.js:345:39)
    at process.processImmediate (node:internal/timers:471:21)

Node.js v18.0.0
```

**Comment by djfarrelly** [comment]
It looks like this is a downstream issue with `smtp-server` for Node 18: https://github.com/nodemailer/smtp-server/blob/master/CHANGELOG.md#v3110-2022-04-28

We haven't yet supported node 18 as it hasn't reached Active LTS as per [the Node release cycle](https://nodejs.org/en/about/releases/), although this should theoretically be a quick fix. Marking as a bug.

**Comment by kossa** [comment]
@djfarrelly Alright I confirm, I used nvm with node 14 it works fine, waiting to support node 18
