### ISSUE TITLE
Unable to display HTML formated email due to JS iFrame access error

### ISSUE THREAD

**Issue by nvandamme** [maildev/maildev#446]
Hi,

I've got a JS error when displaying any email via the web client (localhost:1080) sent to maildev: 

```js
item.js:69 
        
       Uncaught TypeError: Cannot read properties of null (reading 'contentDocument')
    at replaceMediaQueries (item.js:69:30)
    at item.js:51:9
```

Reproduced on Edge 109.0.1518.78 and Firefox 110.0b9

**Comment by nvandamme** [comment]
Ah, sorry i was using the docker image from soulteary, this issue has been already fixed in https://github.com/maildev/maildev/issues/411
Closing.
