### ISSUE TITLE
"To" displays "true" instead of the recipient's email address

### ISSUE THREAD

**Issue by shugyosha89** [maildev/maildev#491]
I tried with multiple different email formats but it always displays "true".

![image](https://github.com/maildev/maildev/assets/59955181/0fce57d7-64a4-4486-8435-d2d2fdca7387)

As seen in the image, the recipient address displays properly in the left panel, but not in the main panel on the right.

Relay also fails due to sending an invalid recipient address:
"501 Invalid RCPT TO address provided"

Maybe it is sending "true" as the recipient address for the relay.

**Comment by designermonkey** [comment]
I'd guess you're using ENV vars, and setting `MAILDEV_AUTO_RELAY: true` as I was.

In the docs I missed that `MAILDEV_AUTO_RELAY` takes an optional email address, so `true` was being passed forward.

I've experimented with `null`, `false` and even`''` as values for that ENV var, all to no avail. Empty and `null` allow the original to email address to be retained (why would you ever want to replace it??), yet when trying to relay via the UI, I get the following error:

```
mail-1    | /home/node/lib/outgoing.js:155
mail-1    |   let recipients = emailObject.envelope.to.map(getAddressFromAddressObject)
mail-1    |                                            ^
mail-1    | 
mail-1    | TypeError: emailObject.envelope.to.map is not a function
mail-1    |     at relayMail (/home/node/lib/outgoing.js:155:44)
mail-1    |     at relayWorker (/home/node/lib/outgoing.js:212:3)
mail-1    |     at /home/node/node_modules/async/dist/async.js:4011:13
mail-1    |     at Object.process (/home/node/node_modules/async/dist/async.js:1674:21)
mail-1    |     at /home/node/node_modules/async/dist/async.js:1532:23
mail-1    |     at /home/node/node_modules/async/dist/async.js:74:45
mail-1    |     at node:internal/process/task_queues:141:7
mail-1    |     at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
mail-1    |     at AsyncResource.runMicrotask (node:internal/process/task_queues:138:8)
mail-1    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Then the container exits.

**Comment by ycatoireDS** [comment]
Hi @shugyosha89  @designermonkey 

I had the same problem.
Maildev tries to relay the mail to the <true> mail address instead of the original one.

You have to remove your line `MAILDEV_AUTO_RELAY: true`, and add this one in your docker-compose.yml : 
`command: ["--auto-relay"]` before environment:

So you have all your smtp relay conf in env variables and you pass the enable directive for auto relay mode with command.

**Comment by djfarrelly** [comment]
Closing as a duplicate of #327 — the root cause is the `MAILDEV_AUTO_RELAY` env var, exactly as @designermonkey and @ycatoireDS diagnosed in the thread. `MAILDEV_AUTO_RELAY` takes an *optional email address*, so setting it to `true` makes MailDev treat `true` as the relay recipient (hence "501 Invalid RCPT TO address" and `true` showing up as the address).

The underlying handling of that env var is tracked in #327 (in the current version `MAILDEV_AUTO_RELAY` actually isn't wired at all — see the analysis there). Fix on your side for now: don't set `MAILDEV_AUTO_RELAY: true`. To enable auto-relay-to-original-recipients, use the `--auto-relay` CLI flag (bare, no value) or a config file; only pass an address when you specifically want to override the recipient. Please follow #327.
