### ISSUE TITLE
[Docker Image] Error permission /tmp

### ISSUE THREAD

**Issue by resyty** [maildev/maildev#494]
When I want to start a docker service with maildev/maildev as the image.
**There is an error at startup :**
`node:internal/fs/utils:350
throw err;
Error: EACCES: permission denied, mkdir '/tmp/maildev-1'
    at Object.mkdirSync (node:fs:1398:3)
    at createMailDir (/home/node/lib/mailserver.js:158:8)
    at mailServer.create (/home/node/lib/mailserver.js:179:3)
    at new module.exports (/home/node/index.js:34:14)
    at Object.<anonymous> (/home/node/bin/maildev:9:17)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/tmp/maildev-1'
 }
Node.js v18.17.0
`
**Here is my configuration :**
`version: '3.7'
services:
  maildev:
    image: maildev/maildev
    networks:
        - reverse_proxy
        - default
    restart: always`

**Comment by jonegard** [comment]
I had a similar issue, adding `user: root` worked for me. It's however possible that there is a better solution to this issue.

**Comment by djfarrelly** [comment]
This is a volume-permission setup issue rather than a code bug, so I'll close it — but here's the cause and the fix.

The container runs as the non-root `node` user (uid 1000). The default mail directory is under `/tmp` (world-writable), so a plain `docker run maildev/maildev` works fine. The `EACCES: mkdir` happens when you point the mail directory at a **bind-mounted/volume path owned by root** (e.g. `MAILDEV_MAIL_DIRECTORY=/mail` with a host dir owned by root) — the `node` user can't create/write there.

Fixes:
- Make the mounted directory writable by uid 1000, e.g. `chown -R 1000:1000 ./maildev-data` on the host (or set appropriate permissions), or
- Use a named Docker volume (Docker initializes ownership more permissively) instead of a bind mount, or
- As a last resort, run the container with `user: root` (works, but less ideal).

(The broader question of making MailDev's default temp-dir handling more robust across users is tracked in #290.) Closing as a configuration issue — happy to help in a fresh issue if it persists with a correctly-owned directory.
